# Use this file to configure your wifi connection(s).
# You should not have to change the lines below

ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config = 1

# WPA/WPA2 secured
network = {
  ssid = "SSID-Wi-Fi"
  psk = "Password-Wi-Fi"
}

# Uncomment the country your Pi is in to activate Wifi in RaspberryPi 3 B+ and above
# For full list see: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
country = RU  # Russia
#country = GB # United Kingdom
#country = CA # Canada
#country = DE # Germany
#country = FR # France
#country = US # United States